node:
  build: .
  volumes:
    # host:containar
    - ./frontend:/frontend/
    - /frontend/node_modules
  working_dir: /frontend
  command: yarn run start
  ports:
    #host:containar
    - "8080:8080"
